### ISSUE TITLE
Update VID and PID

### ISSUE THREAD

**Issue by gotfredsen** [xinabox/xinabox-arduino-board-index#1]
CW03 | VID: 0x04D8 | PID: 0xED5E | SAMD21G18A
CS11 | VID: 0x04D8 | PID: 0xEC75 | SAMD21G18A
CC03 | VID: 0x04D8 | PID: 0xEC72 | SAMD21G18A
CC04 | VID: 0x04D8 | PID: 0xEC71 | SAMD51J18A

**Comment by brendanvanbreda** [comment]
updated with 0b3b9bc

**Comment by brendanvanbreda** [comment]
https://github.com/xinabox/ArduinoCore-samd/commit/1550f6f50da0a1252500ff3981f16e44773c853e
